### ISSUE TITLE
KeyError: 'macro_siglec'

### ISSUE THREAD

**Issue by 964612858j5** [secrierlab/SpottedPy#1]
Hello, I am very honored to use such an excellent algorithm. However, I encountered the following error while running the tutorial spottedPy_multiple_slides.ipynb. I am using Python version 3.9.19 and pandas version 2.2.2. I'm not quite sure what the specific cause of this error is. Could you please give me some advice? Thank you very much!

`>>> for i in tqdm(TME_labels):
...     anndata_breast=sp.create_hotspots(anndata_breast,column_name=i,neighbours_parameters=8,relative_to_batch=True)
... 
  0%|                                                     | 0/3 [00:00<?, ?it/s]/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/squidpy/gr/_utils.py:194: ImplicitModificationWarning: Setting element `.obsp['spatial_connectivities']` of view, initializing view as actual.
  obj[key] = data
/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/squidpy/gr/_utils.py:194: ImplicitModificationWarning: Setting element `.obsp['spatial_connectivities']` of view, initializing view as actual.
  obj[key] = data
/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/squidpy/gr/_utils.py:194: ImplicitModificationWarning: Setting element `.obsp['spatial_connectivities']` of view, initializing view as actual.
  obj[key] = data
/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/squidpy/gr/_utils.py:194: ImplicitModificationWarning: Setting element `.obsp['spatial_connectivities']` of view, initializing view as actual.
  obj[key] = data
/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/squidpy/gr/_utils.py:194: ImplicitModificationWarning: Setting element `.obsp['spatial_connectivities']` of view, initializing view as actual.
  obj[key] = data
/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/squidpy/gr/_utils.py:194: ImplicitModificationWarning: Setting element `.obsp['spatial_connectivities']` of view, initializing view as actual.
  obj[key] = data
/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/squidpy/gr/_utils.py:194: ImplicitModificationWarning: Setting element `.obsp['spatial_connectivities']` of view, initializing view as actual.
  obj[key] = data
/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/squidpy/gr/_utils.py:194: ImplicitModificationWarning: Setting element `.obsp['spatial_connectivities']` of view, initializing view as actual.
  obj[key] = data
/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/squidpy/gr/_utils.py:194: ImplicitModificationWarning: Setting element `.obsp['spatial_connectivities']` of view, initializing view as actual.
  obj[key] = data
/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/squidpy/gr/_utils.py:194: ImplicitModificationWarning: Setting element `.obsp['spatial_connectivities']` of view, initializing view as actual.
  obj[key] = data
/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/squidpy/gr/_utils.py:194: ImplicitModificationWarning: Setting element `.obsp['spatial_connectivities']` of view, initializing view as actual.
  obj[key] = data
/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/squidpy/gr/_utils.py:194: ImplicitModificationWarning: Setting element `.obsp['spatial_connectivities']` of view, initializing view as actual.
  obj[key] = data
/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/squidpy/gr/_utils.py:194: ImplicitModificationWarning: Setting element `.obsp['spatial_connectivities']` of view, initializing view as actual.
  obj[key] = data
/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/squidpy/gr/_utils.py:194: ImplicitModificationWarning: Setting element `.obsp['spatial_connectivities']` of view, initializing view as actual.
  obj[key] = data
/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/squidpy/gr/_utils.py:194: ImplicitModificationWarning: Setting element `.obsp['spatial_connectivities']` of view, initializing view as actual.
  obj[key] = data
/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/squidpy/gr/_utils.py:194: ImplicitModificationWarning: Setting element `.obsp['spatial_connectivities']` of view, initializing view as actual.
  obj[key] = data
/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/squidpy/gr/_utils.py:194: ImplicitModificationWarning: Setting element `.obsp['spatial_connectivities']` of view, initializing view as actual.
  obj[key] = data
/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/squidpy/gr/_utils.py:194: ImplicitModificationWarning: Setting element `.obsp['spatial_connectivities']` of view, initializing view as actual.
  obj[key] = data
/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/squidpy/gr/_utils.py:194: ImplicitModificationWarning: Setting element `.obsp['spatial_connectivities']` of view, initializing view as actual.
  obj[key] = data
/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/squidpy/gr/_utils.py:194: ImplicitModificationWarning: Setting element `.obsp['spatial_connectivities']` of view, initializing view as actual.
  obj[key] = data
/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/squidpy/gr/_utils.py:194: ImplicitModificationWarning: Setting element `.obsp['spatial_connectivities']` of view, initializing view as actual.
  obj[key] = data
/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/squidpy/gr/_utils.py:194: ImplicitModificationWarning: Setting element `.obsp['spatial_connectivities']` of view, initializing view as actual.
  obj[key] = data
/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/squidpy/gr/_utils.py:194: ImplicitModificationWarning: Setting element `.obsp['spatial_connectivities']` of view, initializing view as actual.
  obj[key] = data
/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/squidpy/gr/_utils.py:194: ImplicitModificationWarning: Setting element `.obsp['spatial_connectivities'] of view, initializing view as actual.
  obj[key] = data
 33%|███████████████                              | 1/3 [00:26<00:52, 26.00s/it]
Traceback (most recent call last):
  File "/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'macro_siglec'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/sda1/scRNA_data_center/spRNA/hotspot/SpottedPy/spottedPy/spottedpy.py", line 99, in create_hotspots
    anndata=hotspot_helper.create_hotspots(anndata, column_name, filter_columns, filter_value, neighbours_parameters, p_value, number_components_return, relative_to_batch, number_hotspots, permutation, seed_number)
  File "/sda1/scRNA_data_center/spRNA/hotspot/SpottedPy/spottedPy/hotspot_helper.py", line 157, in create_hotspots
    if any(anndata_filtered.obs[column_name] < 0):
  File "/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/root/mambaforge-pypy3/envs/spottedpy/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'macro_siglec' `

**Comment by 964612858j5** [comment]
Alright, I'm very sorry. I think I found the reason: it's because there is no macro_siglec column in obs.

**Comment by elliewith** [comment]
Thanks for your interest in the tool and raising this! I have now updated the tutorial so this is no longer an option
