### ISSUE TITLE
Installation of Spottedpy

### ISSUE THREAD

**Issue by wangyi0614** [secrierlab/SpottedPy#2]
I was having issues with installing SpottedPy. Below are the input code:

pip intall Spottedpy

only show the .dist-info
![Uploading spottedpy.png…]()

**Comment by elliewith** [comment]
Hi thanks for your interest in our tool!

 Please for now clone the repository:

 _git clone https://github.com/secrierlab/SpottedPy.git_ and then add the location of this folder in sys.path.append("path/to/cloned spottedpy folder") within the tutorial. I am planning on adding it as a package soon.
